name: its-ask-us

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
            echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> $GITHUB_ENV
            echo "PINECONE_INDEX=${{ secrets.PINECONE_INDEX }}" >> $GITHUB_ENV
            echo "PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-v5-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm ci --legacy-peer-deps

      - run: curl https://install.meteor.com/ | sh

      - name: Run Meteor commands
        shell: bash -l {0}
        run: |
          meteor npm install
          meteor npm run lint
          meteor npm run testcafe-ci
